### ISSUE TITLE
installing EasyBuild v1.8.0 - v1.11.1 fails with EasyBuild v1.14 (v1.12 & v1.13 work fine)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-easyblocks#439]
This is caused by some changes in the EasyBuild framework, in particular the inclusion of the (example) hierarchical module naming scheme in `tools/module_naming_scheme/hierarchical_mns.py`.

Module naming scheme modules that are available in the `easybuild.tools.module_naming_scheme` namespace are picked up dynamically by the command line parser (since it wants to be able to list the available module naming schemes). The import of `hierarchical_mns.py` fails however, because it imports stuff that is not available in older EasyBuild versions, or moved into a different place.

The problem manifest itself with a simple `eb --version`, e.g. using EasyBuild v1.11.0, when EasyBuild v1.14.0(dev) is also available in `$PYTHONPATH`.

```
Traceback (most recent call last):
  File "/Users/kehoste/.local/easybuild/software/EasyBuild/1.11.0/lib/python2.7/site-packages/easybuild_framework-1.11.0-py2.7.egg/easybuild/main.py", line 362, in <module>
    main()
  File "/Users/kehoste/.local/easybuild/software/EasyBuild/1.11.0/lib/python2.7/site-packages/easybuild_framework-1.11.0-py2.7.egg/easybuild/main.py", line 87, in main
    eb_go = eboptions.parse_options(args=args)
  File "/Users/kehoste/.local/easybuild/software/EasyBuild/1.11.0/lib/python2.7/site-packages/easybuild_framework-1.11.0-py2.7.egg/easybuild/tools/options.py", line 583, in parse_options
    eb_go = EasyBuildOptions(usage=usage, description=description, prog='eb', envvar_prefix='EASYBUILD', go_args=args)
  File "/Users/kehoste/.local/easybuild/software/EasyBuild/1.11.0/lib/python2.7/site-packages/easybuild_framework-1.11.0-py2.7.egg/vsc/utils/generaloption.py", line 689, in __init__
    self.main_options()
  File "/Users/kehoste/.local/easybuild/software/EasyBuild/1.11.0/lib/python2.7/site-packages/easybuild_framework-1.11.0-py2.7.egg/vsc/utils/generaloption.py", line 764, in main_options
    fn()
  File "/Users/kehoste/.local/easybuild/software/EasyBuild/1.11.0/lib/python2.7/site-packages/easybuild_framework-1.11.0-py2.7.egg/easybuild/tools/options.py", line 187, in config_options
    sorted(avail_module_naming_schemes().keys())),
  File "/Users/kehoste/.local/easybuild/software/EasyBuild/1.11.0/lib/python2.7/site-packages/easybuild_framework-1.11.0-py2.7.egg/easybuild/tools/module_generator.py", line 216, in avail_module_naming_schemes
    import_available_modules('easybuild.tools.module_naming_scheme')
  File "/Users/kehoste/.local/easybuild/software/EasyBuild/1.11.0/lib/python2.7/site-packages/easybuild_framework-1.11.0-py2.7.egg/easybuild/tools/utilities.py", line 121, in import_available_modules
    modules.append(__import__(modpath, globals(), locals(), ['']))
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/module_naming_scheme/hierarchical_mns.py", line 36, in <module>
    from easybuild.tools.module_naming_scheme.toolchain import det_toolchain_compilers, det_toolchain_mpi
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/module_naming_scheme/toolchain.py", line 32, in <module>
    from easybuild.framework.easyconfig.easyconfig import process_easyconfig, robot_find_easyconfig
ImportError: cannot import name process_easyconfig
```

A fix for this would be to improve the isolation of the EasyBuild being installed by improving the easyblock used to install EasyBuild with EasyBuild.

This is being done in #428, and it seems to work, but has to be tested further in different circumstances before it can be merged in, since this affects EasyBuild bootstrapping.

For now, a workaround is to install EasyBuild v1.12.0 or v1.13.0 first using v1.14.0, and then use that if you want to install EasyBuild v1.8.0 through v1.11.1.

**Comment by boegel** [comment]
https://github.com/hpcugent/easybuild-framework/pull/1569 fixes this problem in the case of EasyBuild being 'provided' via `$PYTHONPATH`, e.g. manually or through a module file obtained using the bootstrap install procedure or `eb EasyBuild-<version>.eb`

This problem can still occur when the EasyBuild being used was installed with `easy_install` or `pip`, *and* the EasyBuild being installed is older (and falls in the range specified above).

I'm not going to spend time on fixing the latter though, there's really no point.

So, closing as fixed!
