### ISSUE TITLE
Backtrace when building Python w/ numpy on wrong toolchain

### ISSUE THREAD

**Issue by thiell** [hpcugent/easybuild-easyblocks#716]
Numpy + Intel MKL requires a specific numpy patch. I found a small defect in numpy.py when trying a non-intel toolchain (I know, my bad, a mistake!):

https://gist.github.com/thiell/8acdaa4c4c5194c8b24d

An exception is already in place a few lines below to explain the user a specific patch is needed, but is not raised with the current code. Seems easy to fix, I plan to submit a patch through a pull request ASAP.

**Comment by boegel** [comment]
@thiell: if the output you want to refer to is reasonable small, it's better to include it in the issue itself, for future reference (the gist may be removed, yielding loss of context)

```
$ eb --configfiles=/tmp/config.cfg SWIG-3.0.7-foss-2015a-Python-2.7.9.eb  --try-toolchain=intel,2015.5.223 --robot intel-2015.5.223/
== temporary log file in case of crash /tmp/eb-hHtY6G/easybuild-bS1o_a.log
== resolving dependencies ...
== processing EasyBuild easyconfig /tmp/eb-hHtY6G/tweaked_easyconfigs/Python-2.7.9-intel-2015.5.223.eb
== building and installing MPI/intel/2015.5.223-GNU-4.9.2-2.25/impi/5.0.3.049/Python/2.7.9...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
ERROR: Traceback (most recent call last):
  File "/global/software/Core/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/main.py", line 112, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/global/software/Core/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyblock.py", line 1994, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/global/software/Core/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyblock.py", line 1934, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/global/software/Core/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyblock.py", line 1816, in run_step
    m(self)
  File "/global/software/Core/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyblock.py", line 1897, in <lambda>
    (EXTENSIONS_STEP, 'taking care of extensions', [lambda x: x.extensions_step()], False),
  File "/global/software/Core/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyblock.py", line 1483, in extensions_step
    txt = inst.run()
  File "/global/software/Core/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_easyblocks-2.3.0-py2.6.egg/easybuild/easyblocks/generic/pythonpackage.py", line 241, in run
    self.configure_step()
  File "/global/software/Core/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_easyblocks-2.3.0-py2.6.egg/easybuild/easyblocks/n/numpy.py", line 130, in configure_step
    for patch in self.patches:
TypeError: 'NoneType' object is not iterable
```

**Comment by boegel** [comment]
Follow-up via #717
